import React, { useEffect, useState } from 'react';
import { 
  Wallet, 
  TrendingUp, 
  ArrowDownLeft, 
  ArrowUpRight, 
  IndianRupee,
  Clock,
  Zap,
  Copy,
  Check,
  Film,
  ImageIcon,
  Eye,
  Layers,
} from 'lucide-react';
import { supabase } from '../lib/supabase';

const Earnings: React.FC = () => {
  const [walletBalance, setWalletBalance] = useState(0);
  const [transactions, setTransactions] = useState<any[]>([]);
  const [rateCard, setRateCard] = useState<any>(null);
  const [tier, setTier] = useState('nano');
  const [loading, setLoading] = useState(true);
  const [copiedRate, setCopiedRate] = useState<string | null>(null);
  const [copiedAll, setCopiedAll] = useState(false);

  useEffect(() => {
    const fetchData = async () => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) return;

      try {
        const backendUrl = import.meta.env.VITE_BACKEND_URL || 'https://campayn-backend.onrender.com';
        const res = await fetch(`${backendUrl}/api/auth/creator/dashboard/${user.id}`);
        const data = await res.json();
        if (data.success) {
          setWalletBalance(data.wallet?.balance || 0);
          setRateCard(data.rateCard?.rates || {});
          setTier(data.rateCard?.tier || 'nano');
        }

        // Fetch transactions
        const { data: wallet } = await supabase
          .from('wallets')
          .select('id')
          .eq('user_id', user.id)
          .maybeSingle();

        if (wallet) {
          const { data: txns } = await supabase
            .from('wallet_transactions')
            .select('*')
            .eq('wallet_id', wallet.id)
            .order('created_at', { ascending: false })
            .limit(20);
          
          setTransactions(txns || []);
        }
      } catch (err) {
        console.error('Earnings fetch error:', err);
      }
      setLoading(false);
    };
    fetchData();
  }, []);

  const handleCopyRate = (type: string, rate: number) => {
    navigator.clipboard.writeText(`₹${rate.toLocaleString('en-IN')} per ${type}`);
    setCopiedRate(type);
    setTimeout(() => setCopiedRate(null), 2000);
  };

  const handleCopyAll = () => {
    const text = `📋 My Rate Card (${tier.toUpperCase()} Tier)\n\n` +
      `🎬 Reel: ₹${(rateCard?.reel || 0).toLocaleString('en-IN')}\n` +
      `📸 Post: ₹${(rateCard?.post || 0).toLocaleString('en-IN')}\n` +
      `📱 Story: ₹${(rateCard?.story || 0).toLocaleString('en-IN')}\n` +
      `🎠 Carousel: ₹${(rateCard?.carousel || 0).toLocaleString('en-IN')}\n\n` +
      `Generated by Campayn — campayn.tech`;
    navigator.clipboard.writeText(text);
    setCopiedAll(true);
    setTimeout(() => setCopiedAll(false), 3000);
  };

  const totalEarned = transactions
    .filter(t => t.transaction_type === 'credit')
    .reduce((sum, t) => sum + parseFloat(t.amount || 0), 0);

  const pendingPayouts = transactions
    .filter(t => t.transaction_type === 'credit' && t.description?.includes('pending'))
    .reduce((sum, t) => sum + parseFloat(t.amount || 0), 0);

  if (loading) {
    return (
      <div className="space-y-8 animate-pulse">
        <div className="h-10 bg-white/5 rounded-xl w-1/3" />
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {[...Array(3)].map((_, i) => <div key={i} className="h-32 bg-white/5 rounded-2xl" />)}
        </div>
      </div>
    );
  }

  const rateItems = [
    { type: 'Reel', icon: <Film size={20} />, rate: rateCard?.reel || 500, color: 'from-pink-500 to-rose-500', desc: 'Short-form video' },
    { type: 'Post', icon: <ImageIcon size={20} />, rate: rateCard?.post || 300, color: 'from-blue-500 to-cyan-500', desc: 'Feed post' },
    { type: 'Story', icon: <Eye size={20} />, rate: rateCard?.story || 200, color: 'from-amber-500 to-orange-500', desc: '24h story' },
    { type: 'Carousel', icon: <Layers size={20} />, rate: rateCard?.carousel || 400, color: 'from-emerald-500 to-teal-500', desc: 'Multi-image' },
  ];

  return (
    <div className="space-y-8 animate-in fade-in duration-700">
      {/* Header */}
      <div>
        <h1 className="text-3xl font-bold">Earnings</h1>
        <p className="text-slate-400 mt-1">Track your income and manage your rate card.</p>
      </div>

      {/* Summary Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="glass-card p-6">
          <div className="flex items-center gap-3 mb-4">
            <div className="p-3 rounded-xl bg-emerald-400/10">
              <Wallet className="text-emerald-400" size={22} />
            </div>
            <span className="text-sm text-slate-400 uppercase tracking-wider">Available Balance</span>
          </div>
          <h2 className="text-3xl font-bold text-emerald-400">₹{walletBalance.toLocaleString('en-IN')}</h2>
        </div>
        <div className="glass-card p-6">
          <div className="flex items-center gap-3 mb-4">
            <div className="p-3 rounded-xl bg-violet-400/10">
              <TrendingUp className="text-violet-400" size={22} />
            </div>
            <span className="text-sm text-slate-400 uppercase tracking-wider">Total Earned</span>
          </div>
          <h2 className="text-3xl font-bold">₹{totalEarned.toLocaleString('en-IN')}</h2>
        </div>
        <div className="glass-card p-6">
          <div className="flex items-center gap-3 mb-4">
            <div className="p-3 rounded-xl bg-amber-400/10">
              <Clock className="text-amber-400" size={22} />
            </div>
            <span className="text-sm text-slate-400 uppercase tracking-wider">Pending Payouts</span>
          </div>
          <h2 className="text-3xl font-bold text-amber-400">₹{pendingPayouts.toLocaleString('en-IN')}</h2>
        </div>
      </div>

      {/* Smart Rate Card (Full) */}
      <div className="glass-card p-8">
        <div className="flex flex-col md:flex-row md:items-center justify-between mb-8">
          <div className="flex items-center gap-3">
            <Zap className="text-amber-400" size={24} />
            <div>
              <h3 className="text-2xl font-bold">Smart Rate Card</h3>
              <p className="text-slate-400 text-sm mt-1">Auto-calculated from your real metrics • Indian market benchmarks</p>
            </div>
          </div>
          <div className="flex items-center gap-3 mt-4 md:mt-0">
            <span className="text-xs font-bold uppercase tracking-wider px-3 py-1.5 bg-gradient-to-r from-violet-500/10 to-purple-500/10 border border-violet-500/20 rounded-lg text-violet-400">
              {tier} tier
            </span>
            <button
              onClick={handleCopyAll}
              className="flex items-center gap-2 px-4 py-2 rounded-xl bg-white/5 hover:bg-white/10 border border-white/10 transition-all text-sm font-medium"
            >
              {copiedAll ? <><Check size={14} className="text-emerald-400" /> Copied!</> : <><Copy size={14} /> Share Rate Card</>}
            </button>
          </div>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {rateItems.map(item => (
            <button
              key={item.type}
              onClick={() => handleCopyRate(item.type, item.rate)}
              className="relative group p-6 rounded-2xl border border-white/10 hover:border-white/20 transition-all text-left overflow-hidden"
            >
              <div className={`absolute inset-0 bg-gradient-to-br ${item.color} opacity-0 group-hover:opacity-10 transition-opacity`} />
              <div className="relative z-10">
                <div className="flex items-center justify-between mb-3">
                  <div className="p-2 rounded-lg bg-white/5">{item.icon}</div>
                  {copiedRate === item.type ? (
                    <Check size={16} className="text-emerald-400" />
                  ) : (
                    <Copy size={14} className="text-slate-600 group-hover:text-slate-400 transition-colors" />
                  )}
                </div>
                <p className="text-sm font-medium text-slate-300 mb-1">{item.type}</p>
                <p className="text-3xl font-bold">₹{item.rate.toLocaleString('en-IN')}</p>
                <p className="text-xs text-slate-500 mt-2">{item.desc}</p>
              </div>
            </button>
          ))}
        </div>
      </div>

      {/* Transaction History */}
      <div className="glass-card p-8">
        <h3 className="text-xl font-bold mb-6">Transaction History</h3>
        {transactions.length === 0 ? (
          <div className="text-center py-12">
            <IndianRupee className="mx-auto text-slate-600 mb-4" size={48} />
            <h3 className="text-lg font-bold text-slate-300">No transactions yet</h3>
            <p className="text-slate-500 mt-2">Complete campaigns to start earning!</p>
          </div>
        ) : (
          <div className="space-y-3">
            {transactions.map((txn) => (
              <div key={txn.id} className="flex items-center justify-between p-4 rounded-xl hover:bg-white/5 transition-colors">
                <div className="flex items-center gap-4">
                  <div className={`p-2 rounded-lg ${txn.transaction_type === 'credit' ? 'bg-emerald-500/10' : 'bg-red-500/10'}`}>
                    {txn.transaction_type === 'credit' 
                      ? <ArrowDownLeft size={18} className="text-emerald-400" />
                      : <ArrowUpRight size={18} className="text-red-400" />
                    }
                  </div>
                  <div>
                    <p className="font-medium">{txn.description || 'Transaction'}</p>
                    <p className="text-xs text-slate-500">{new Date(txn.created_at).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })}</p>
                  </div>
                </div>
                <span className={`text-lg font-bold ${txn.transaction_type === 'credit' ? 'text-emerald-400' : 'text-red-400'}`}>
                  {txn.transaction_type === 'credit' ? '+' : '-'}₹{parseFloat(txn.amount || 0).toLocaleString('en-IN')}
                </span>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

export default Earnings;
